export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";

export const IMAGEUPDATE = "IMAGEUPDATE";
export const IMAGEUPDATEENTERPRISE = "IMAGEUPDATEENTERPRISE";
export const IMAGEUPDATESTORE = "IMAGEUPDATESTORE";

export const UPDATEFULLNAMEANDBIO = "UPDATEFULLNAMEANDBIO";
export const UPDATEFNANDBIOENTERPRISE = "UPDATEFNANDBIOENTERPRISE";
export const UPDATEFNANDBIOSTORE = "UPDATEFNANDBIOSTORE";

export const UPDATESOCIALMEDIA = "UPDATESOCIALMEDIA";
export const UPDATEINFOENTERPRISE = "UPDATEINFOENTERPRISE";
export const UPDATESTOREPRODUCTS = "UPDATESTOREPRODUCTS";
export const PULLINFO = "PULLINFO";
export const LOGOUT = "LOGOUT";
export const PULLINFOVIEW = "PULLINFOVIEW";
export const CHANGETOVN = "CHANGETOVN";
export const CHANGETOEN = "CHANGETOEN";

export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_BG_COLOR_ENTERPRISE = "SET_BG_COLOR_ENTERPRISE";
export const SET_BG_COLOR_STORE = "SET_BG_COLOR_STORE";

export const SET_BACKGROUND_COLOR_STYLE = "SET_BACKGROUND_COLOR_STYLE";
export const SET_BG_COLOR_STYLE_ENTER = "SET_BG_COLOR_STYLE_ENTER";
export const SET_BG_COLOR_STYLE_STORE = "SET_BG_COLOR_STYLE_STORE";

export const DISPATCH_ICON_STYLE = "DISPATCH_ICON_STYLE";
export const SET_ICON_ENTERPRISE = "SET_ICON_ENTERPRISE";
export const SET_ICON_STORE = "SET_ICON_STORE";

export const SET_BACKGROUND_IMAGE = "SET_BACKGROUND_IMAGE";
export const SET_BGIMG_ENTERPRISE = "SET_BGIMG_ENTERPRISE";
export const SET_BGIMG_STORE = "SET_BGIMG_STORE";

export const SET_REDIRECT_MODE = "SET_REDIRECT_MODE";

export const DISPATCH_LOGIN_INFO = "DISPATCH_LOGIN_INFO";
export const DISPATCH_USER_INFO = "DISPATCH_USER_INFO";
export const DISPATCH_REDIRECT_LINK = "DISPATCH_REDIRECT_LINK";
export const REDIRECT_SAVE_CONTACT = "DISPATCH_REDIRECT_SAVE_CONTACT";
export const DISPATCH_SERIALARRAY = "DISPATCH_SERIALARRAY";

export const DISPATCH_TOKEN = "DISPATCH_TOKEN";
export const DISPATCH_ANALYTIC_DATA = "DISPATCH_ANALYTIC_DATA";
export const DISPATCH_MESSAGE_DATA = "DISPATCH_MESSAGE_DATA";

export const DEACTIVATE_PAGE = "DEACTIVATE_PAGE";
export const ACTIVATE_PAGE = "ACTIVATE_PAGE";
export const SET_ENTERPRISEPAGE = "SET_ENTERPRISEPAGE";
export const SET_STOREPAGE = "SET_STOREPAGE";
export const SET_GALLERYPAGE = "SET_GALLERYPAGE";
export const SET_TEMPDATA = "SET_TEMPDATA";
export const CHANGE_B2B_TAB = "CHANGE_B2B_TAB";

export const PERSONAL_PAGE_VISITED = "PERSONAL_PAGE_VISITED";
export const COMPANY_PAGE_VISITED = "COMPANY_PAGE_VISITED";
export const STORE_PAGE_VISITED = "STORE_PAGE_VISITED";
export const STORE_PAGE_ACTIVATE = "STORE_PAGE_ACTIVATE";

export const SET_NEW_NOTE = "SET_NEW_NOTE";
export const SET_PIN = "SET_PIN";

export const GALLERY_PAGE_ACTIVATE = "GALLERY_PAGE_ACTIVATE";
